# Generated by Django 6.0.5 on 2026-05-12 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resend_inbound_address', models.EmailField(blank=True, default='', max_length=254)),
                ('ai_extraction_enabled', models.BooleanField(default=True)),
                ('ai_extraction_prompt', models.TextField(default='Extract key information from this email and its attachments. Return structured JSON with: dates, amounts, names, addresses, and any other relevant fields.')),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('notification_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User settings',
            },
        ),
    ]
