# Generated by Django 6.0.5 on 2026-05-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='imap_host',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='imap_password',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='imap_port',
            field=models.IntegerField(default=993),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='imap_use_ssl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='imap_username',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
