# Generated by Django 6.0.5 on 2026-05-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersettings_imap_host_usersettings_imap_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='sync_filter_to_address',
            field=models.CharField(blank=True, default='', help_text='Only sync emails sent to this address. Leave blank to sync all.', max_length=500),
        ),
    ]
