# Generated by Django 6.0.5 on 2026-05-12 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_field', models.CharField(choices=[('sender', 'Sender'), ('subject', 'Subject'), ('body', 'Body'), ('attachment_name', 'Attachment Name'), ('extracted_text', 'Extracted Text')], max_length=30)),
                ('operator', models.CharField(choices=[('contains', 'Contains'), ('equals', 'Equals'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('regex', 'Regex')], max_length=20)),
                ('trigger_value', models.CharField(max_length=500)),
                ('action_type', models.CharField(choices=[('label', 'Add Label'), ('forward', 'Forward Email'), ('webhook', 'Call Webhook'), ('extract', 'Extract Data (AI)'), ('notify', 'Send Notification')], max_length=20)),
                ('action_config', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=10)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_executions', to='mail.email')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automations.automationrule')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
